const advices = { // oggetto con suggerimenti:
'01d': 'Make sure to take the sun lotion! 🌞',
'01n': 'Good night 🌚',
'02d': 'Sun seems a little bit shy today 😒',
'02n': 'Moon seems shy as well... 🌜',
'03d': 'Lonely clouds... 🌥️',
'03n': 'Sweet dreams 🛌',
'04d': 'Grey sky. ☁️',
'04n': 'Everything is covered, innit? 👁️‍🗨️',
'09d': 'Do not forget your umbrella! ☔',
'09n': 'Cover yourself! 🧣',
'10d': 'Umbrella needed mate... 🌂',
'10n': 'Gonna be freezing, yikes! 🥶',
'11d': 'Incoming Lightning bolts! 🌩️',
'11n': 'Gotta be some thunder strikes! ⛈️',
'13d': 'Time to make a snow-man! ☃️',
'13n': 'Right night for snuggles and cuddles! 😻',
'50d': 'Cannot see a thing! 🌫️',
'50n': 'Watch out where you go! 🕳️'
}